#---------------------------------------------------------------------
#Github Actions HomeWork Globallogic
#
#Ihor Korobov
#
#luck7454@gmail.com
#---------------------------------------------------------------------
name: My-GitHubActions-Basics

on: 
  push:
    branches: 
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message in Testing
      run : echo "Hello World from Testing job"
    
  
  my_deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message in Deploy
      run : echo "Hello World from Deploy job"
    
