#---------------------------------------------------------------------
#Github Actions HomeWork Globallogic
#
#Ihor Korobov
#
#luck7454@gmail.com
#---------------------------------------------------------------------
name: GitHubActions-GL

on: 
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message in Testing
      run : echo "Hello World from Testing job"
  
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print Hello Message in Deploy
      run : echo "Hello World from Deploy job"
      
